### PR TITLE
CUSUM Level Analysis in MOSAIC

### PR DESCRIPTION
**Pull request by shadowk29**
Implements the CUSUM algorithm (used by OpenNanopore for example) in MOSAIC. This approach sacrifices including system information in the analysis in favor of much faster fitting of single- and multi-level events.

Some known issues with CUSUM:

1. If the duration of a sub-event is shorter than a few RC rise times, the averaging will underestimate the extent of the current change. I have not yet found a satisfactory solution for this issue, but for longer events CUSUM should achieve very similar output to the fitting employed elsewhere in MOSAIC.
2. CUSUM assumes an instantaneous transition between current states. As a result, if the RC rise time of the system is large, CUSUM can trigger and detect intermediate states during the change time. This can usually be mitigated by playing with the algorithm sensitivity settings.
3. If the event is very long, CUSUM will eventually trigger even if there is no real change, leading to artificially high nStates values for an event. This is a consequence of using a statistical t-test which can have false positives, and can in some cases be mitigated by reducing the sensitivity.

To use it requires two new settings:

{
    "cusumLevelAnalysis": {
        "StepSize": 3.0, 
        "Threshold": 3.0
    }
}

StepSize is the number of baseline standard deviations are considered significant (3 is usually a good starting point). Threshold is the sensitivity of the algorithm, (lower is more sensitive, a good starting point is to set it equal to StepSize). CUSUM will detect jumps that are smaller than StepSize, but they will have to be sustained longer. Threshold can be thought of, very roughly, as roughly proportional to the length of time a subevent must be sustained for it to be detected.

You can read about the algorithm here: http://pubs.rsc.org/en/Content/ArticleLanding/2012/NR/c2nr30951c#!divAbstract

### CODE REVIEW

**Comment by abalijepalli** [comment]
This looks great. Could you update the docstring for the cusum class. It currently has the multi-state text. You could use a lot of text from your pull request comment above.

**Comment by shadowk29** [comment]
What do you mean by the docstring?

**Comment by abalijepalli** [comment]
Exactly. When we generate documentation, that string gets merged into the HTML or PDF. For an example, see binTrajIO (https://usnistgov.github.io/mosaic/html/api-doc/mosaic.traj.html#mosaic-bintrajio-module) and its corresponding source (https://github.com/usnistgov/mosaic/blob/devel-1.0/mosaic/binTrajIO.py).

**Comment by shadowk29** [comment]
Done. Looks like it updates the pull request as well, cool.

**Pull request merged**
