### PR TITLE
CUSUM: Updated metadata representation

### PR DESCRIPTION
**Pull request by abalijepalli**
The metadata in CUSUM is updated to be consistent with the way other algorithms in MOSAIC represent states in the following way:
1. `CurrentStep` is relative to the open state
2. `EventDelay` removes padding (baseline) before and after the event as states.
3. `NStates` is updated to reflect 1. and 2.

Preliminary analysis with the PEG28 reference data was successful (visualization in Mathematica is show below).

untitled

### CODE REVIEW

**Comment by shadowk29** [comment]
I implemented vanilla CUSUM, but there might be a few tricks to improve it. One thing I have noticed with CUSUM is that because it by default averages over the entire segment between two detected jumps in order to obtain a current step, it can underestimate levels since it averages over the RC rise time as well (you can sort of see this in your plot above). You may find it beneficial to change this behavior and only average over the last half of an event for your current levels.

**Comment by shadowk29** [comment]
However, I see no problems with your code changes

**Comment by abalijepalli** [comment]
That's a good point. We can certainly improve the algorithm over time.

I wanted to get the metadata in a somewhat final form before we develop the visualization in the GUI. I'll go ahead and merge this code.

**Comment by shadowk29** [comment]
Please see my edited comment above.

**Pull request merged**
