### PR TITLE
updated minstep to be half of the step size

### PR DESCRIPTION
**Pull request by shadowk29**
updated minstep to half of stepsize by default

### CODE REVIEW

**Comment by shadowk29** [comment]
I also added the MinLength parameter to cusum init guess function

**Comment by shadowk29** [comment]
in the winFitEvent() function the FitIters option was not being used. Added maxfev=self.FitIters to curve_fit to avoid infinite loop.

**Comment by abalijepalli** [comment]
We may not want to scale theMinLength parameter. Since we are generating the initial guesses for ADEPT, we don't want to reject the very short states even if they are mischaracterized. I think ADEPT should be able to optimize the fit from less than optimal initial guesses.

**Comment by shadowk29** [comment]
The problem is that CUSUM will detect additional states in the rise time if we are not careful about the MinLength parameter. This will lead to artificially high numbers of states and even if adept does minimize the fit function, it might not be physical.

**Pull request merged**
