### PR TITLE
Implemented adaptive threshold algorithm to mirror OpenNanopore implemen...

### PR DESCRIPTION
**Pull request by shadowk29**
Adaptive CUSUM threshold implementation for testing. CUSUM now requires two threshold settings (MinThreshold and MaxThreshold) in order to function. Actual threshold used changes for each event and is stored in the DB.

### CODE REVIEW

**Comment by shadowk29** [comment]
I also fixed a bug where the negative decision array was not getting reset - I think this might be responsible for a preponderence of rise time events on negative current jumps

**Comment by shadowk29** [comment]
The third commit improves averaging of CUSUM levels and causes CUSUM to ignore rise time events. It works well for longer events, but requires more testing for corner cases. Levels shorter than the new parameter will be missed.

CUSUM settings now look like this:

"cusumLevelAnalysis": {
                "StepSize"              : "4.0",
                "MinThreshold"          : "3.0",
		"MaxThreshold"		: "20.0",
		"MinLengthMS"		: "0.04"
        }

**Comment by abalijepalli** [comment]
I would recommend setting MinLength to the number of data points instead of ms, to be consistent with other algorithms in the code. Eventually, we may migrate these parameters to some multiple of the RC constant.

**Comment by shadowk29** [comment]
Done

**Pull request merged**
